apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agentos

resources:
  - namespace.yaml
  - config.yaml
  - server.yaml

commonLabels:
  app.kubernetes.io/name: agentos
  app.kubernetes.io/part-of: agentos